name: Daily Reminder Emails

on:
  schedule:
    - cron: '15 4 * * *'  # Runs daily at 04:15 UTC
  workflow_dispatch: {}

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Decode Secret JSON from Base64
      run: |
        mkdir -p data
        echo "${{ secrets.EVENT_JSON_B64 }}" | base64 -d > data/events.json

    - name: Create SMTP Config JSON
      env:
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
      run: |
        echo "{\"smtp_host\": \"smtp.gmail.com\", \"smtp_port\": 587, \"smtp_user\": \"${SMTP_USER}\", \"smtp_pass\": \"${SMTP_PASS}\"}" > data/config.json

    - name: Show events.json (Debugging)
      run: |
        echo "Contents of data/events.json:"
        cat data/events.json

    - name: Debug decode
      run: |
        echo "Decoding secret:"
        echo "${{ secrets.EVENTS_JSON_B64 }}" | head -c 60
        echo "${{ secrets.EVENTS_JSON_B64 }}" | base64 -d | head -c 100


    - name: Run Reminder App
      run: |
        python src/reminder.py
