name: Daily Reminder Emails

on:
  schedule:
    - cron: '15 4 * * *'  # Runs daily at 04:15 UTC or 00:15 EST
  workflow_dispatch: {}

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Decode Secret JSON from Base64
      run: |
        mkdir -p data
        echo "${{ secrets.EVENTS_JSON_B64 }}" | base64 -d > data/events.json

    - name: Create SMTP Config JSON
      env:
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
      run: |
        echo "{\"smtp_host\": \"smtp.gmail.com\", \"smtp_port\": 587, \"smtp_user\": \"${SMTP_USER}\", \"smtp_pass\": \"${SMTP_PASS}\"}" > data/config.json

    - name: Run Reminder App
      run: |
        python src/reminder.py
